name: Go licenses check
description: Uses `github.com/google/go-licenses` to analyze the dependency tree of a Go package/binary.
author: joeig
branding:
  icon: check-square
  color: orange
inputs:
  allowed-licenses:
    description: |
      Comma-separated list of allowed license names. Can't be used in combination with `disallowed-types`.
      Supported license names: [github.com/google/licenseclassifier](https://github.com/google/licenseclassifier/blob/e6a9bb99b5a6f71d5a34336b8245e305f5430f99/license_type.go)
    default: ""
  application-version:
    description: The desired version of `github.com/google/go-licenses`.
    default: "v1.6.0"
  confidence-threshold:
    description: Minimum confidence required in order to positively identify a license.
    default: "0.9"
  disallowed-types:
    description: |
      Comma-separated list of disallowed license types. Can't be used in combination with `allowed_licenses`.
      Allowed values: `forbidden`, `notice`, `permissive`, `reciprocal`, `restricted`, `unencumbered`, `unknown`
      Supported license types: [github.com/google/licenseclassifier](https://github.com/google/licenseclassifier/blob/e6a9bb99b5a6f71d5a34336b8245e305f5430f99/license_type.go)
    default: forbidden,unknown
  ignore-packages:
    description: Comma-separated list of package path prefixes to be ignored. Dependencies from the ignored packages are still checked.
    default: ""
  include-tests:
    description: Include packages only imported by testing code.
    default: "true"
  package:
    description: The package to be checked.
    default: ./...
  working-directory:
    description: The working directory.
    default: ./
runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Install go-licenses
      run: go install github.com/google/go-licenses@${{ inputs.application-version }}
      shell: bash
    - name: Generate report
      run: |
        TEMPLATE="$(mktemp)"
        cat > "${TEMPLATE}" <<EOF
        Presumed licenses based on the given parameters:
        
        | Name | Version | License |
        | ---- | ------- | ------- |
        {{ range . -}}
        | {{ .Name }} | {{ .Version }} | [{{ .LicenseName }}]({{ .LicenseURL }}) |
        {{ end }}
        EOF
        go-licenses report --template="${TEMPLATE}" --confidence_threshold="${{ inputs.confidence-threshold }}" --ignore="${{ inputs.ignore-packages }}" --include_tests="${{ inputs.include-tests }}" "${{ inputs.package }}" >> "${GITHUB_STEP_SUMMARY}"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Check licenses
      run: |
        RESULT="$(mktemp)"
        if ! go-licenses check --allowed_licenses="${{ inputs.allowed-licenses }}" --disallowed_types="${{ inputs.disallowed-types }}" --confidence_threshold="${{ inputs.confidence-threshold }}" --ignore="${{ inputs.ignore-packages }}" --include_tests="${{ inputs.include-tests }}" "${{ inputs.package }}" >> "${RESULT}"; then
          RESULT_CONTENT="$(cat "${RESULT}")"
          echo "" >> "${GITHUB_STEP_SUMMARY}"
          echo "## ❌ License check failed" >> "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"
          echo "${RESULT_CONTENT}" >> "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"
          echo "::error::License check failed. See job summary for details."
          exit 1
        fi
      shell: bash
      working-directory: ${{ inputs.working-directory }}
