name: Go licenses check
description: Uses `github.com/google/go-licenses` to analyze the dependency tree of a Go package/binary.
author: joeig
branding:
  icon: check-square
  color: orange
inputs:
  allowed-licenses:
    description: |
      Comma-separated list of allowed license names. Can't be used in combination with `disallowed-types`.
      Supported license names: [github.com/google/licenseclassifier](https://github.com/google/licenseclassifier/blob/e6a9bb99b5a6f71d5a34336b8245e305f5430f99/license_type.go)
    default: ""
  confidence-threshold:
    description: Minimum confidence required in order to positively identify a license.
    default: "0.9"
  disallowed-types:
    description: |
      Comma-separated list of disallowed license types. Can't be used in combination with `allowed_licenses`.
      Allowed values: `forbidden`, `notice`, `permissive`, `reciprocal`, `restricted`, `unencumbered`, `unknown`
      Supported license types: [github.com/google/licenseclassifier](https://github.com/google/licenseclassifier/blob/e6a9bb99b5a6f71d5a34336b8245e305f5430f99/license_type.go)
    default: forbidden,unknown
  ignore-packages:
    description: Comma-separated list of package path prefixes to be ignored. Dependencies from the ignored packages are still checked.
    default: ""
  include-tests:
    description: Include packages only imported by testing code.
    default: "true"
  package:
    description: The package to be checked.
    default: ./...
  working-directory:
    description: The working directory.
    default: ./
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: "1.24"
    - run: go install github.com/google/go-licenses@v1.6.0
      shell: bash
    - run: go-licenses report --confidence_threshold="${{ inputs.confidence-threshold }}" --ignore="${{ inputs.ignore-packages }}" --include_tests="${{ inputs.include-tests }}" "${{ inputs.package }}"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - run: go-licenses check --allowed_licenses="${{ inputs.allowed-licenses }}" --disallowed_types="${{ inputs.disallowed-types }}" --confidence_threshold="${{ inputs.confidence-threshold }}" --ignore="${{ inputs.ignore-packages }}" --include_tests="${{ inputs.include-tests }}" "${{ inputs.package }}"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
