name: test
on:
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-$${{ github.pull_request.number || github.run_id }}"
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  test-mit:
    name: Test allowed MIT license
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        with:
          working-directory: ./testdata/package-mit/
          allowed-licenses: MIT
          disallowed-types: ""
    continue-on-error: true
  test-unknown:
    name: Test disallowed unknown license
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        with:
          working-directory: ./testdata/package-unknown/
          disallowed-types: unknown
    continue-on-error: true
